name: Run test_utils.py

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Vanilla install from conda
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yaml
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        mamba env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        python3 -m unittest tests.test_utils
